version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/mikeee/chocohelpers"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"