name: Run Tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  go-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Test
        run: go test -race -v ./...
  go-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Test
        run: go test -race -v ./...
  go-test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Test
        run: go test -race -v ./...